"""Build the shared gazetteer artifacts from open data.

Sources: OSM Overpass (Ukrainian city/town names, name:uk) + pymorphy3 inflection
(build-time only) + KMU transliteration. Emits:
  - crawler/crawler/discovery/gazetteer.json  (form-map for the crawler matcher)
  - admin/src/constants/gazetteer.js          (names-only list for the admin dropdown)

Run:  cd crawler && python scripts/build_gazetteer.py
"""
import json
import pathlib
import sys

import httpx
import pymorphy3

from crawler.discovery.homograph_overrides import FORCE_MARKER, FORCE_PERMISSIVE

ROOT = pathlib.Path(__file__).resolve().parents[2]
CRAWLER_OUT = ROOT / "crawler" / "crawler" / "discovery" / "gazetteer.json"
ADMIN_OUT = ROOT / "admin" / "src" / "constants" / "gazetteer.js"

OVERPASS_ENDPOINTS = [
    "https://overpass-api.de/api/interpreter",
    "https://overpass.kumi.systems/api/interpreter",
]
QUERY = """
[out:json][timeout:180];
area["ISO3166-1"="UA"][admin_level=2]->.ua;
( node["place"~"^(city|town)$"]["name:uk"](area.ua); );
out tags;
"""

CASES = ["gent", "datv", "accs", "loct", "ablt"]
# KMU-2010 Ukrainian -> Latin (multi-char first).
TRANSLIT = [
    ("зг", "zgh"),
    ("ж", "zh"), ("х", "kh"), ("ц", "ts"), ("ч", "ch"), ("ш", "sh"), ("щ", "shch"),
    ("ю", "iu"), ("я", "ia"), ("є", "ie"), ("ї", "i"), ("й", "i"),
    ("а", "a"), ("б", "b"), ("в", "v"), ("г", "h"), ("ґ", "g"), ("д", "d"), ("е", "e"),
    ("з", "z"), ("и", "y"), ("і", "i"), ("к", "k"), ("л", "l"), ("м", "m"), ("н", "n"),
    ("о", "o"), ("п", "p"), ("р", "r"), ("с", "s"), ("т", "t"), ("у", "u"), ("ф", "f"),
    ("ь", ""), ("'", ""), ("’", ""),
]
ALT_TRANSLIT = {
    "Київ": ["kyiv", "kiev"], "Львів": ["lviv", "lvov"], "Одеса": ["odesa", "odessa"],
    "Харків": ["kharkiv", "kharkov"], "Дніпро": ["dnipro", "dnepr"],
    "Запоріжжя": ["zaporizhzhia", "zaporozhye"], "Миколаїв": ["mykolaiv", "nikolaev"],
    "Чернігів": ["chernihiv", "chernigov"], "Чернівці": ["chernivtsi"],
}

_morph = pymorphy3.MorphAnalyzer(lang="uk")


def transliterate(name: str) -> str:
    s = name.lower()
    for src, dst in TRANSLIT:
        s = s.replace(src, dst)
    return "".join(ch for ch in s if ch.isascii()).strip()


def inflect_forms(name: str) -> set[str]:
    words = name.split()
    forms = {name.lower()}
    for case in CASES:
        parts, ok = [], True
        for w in words:
            infl = _morph.parse(w)[0].inflect({case})
            if infl is None:
                ok = False
                break
            parts.append(infl.word)
        if ok:
            forms.add(" ".join(parts))
    return forms


_ADJV = {"ADJF", "ADJS", "COMP", "VERB", "INFN", "PRTF", "PRTS", "GRND", "ADVB"}


def is_common(form: str) -> bool:
    # A form collides with a common word if pymorphy can read it as an
    # adjective/verb (city names are nouns). Multiword names are low-collision.
    if " " in form:
        return False
    return any(p.tag.POS in _ADJV for p in _morph.parse(form))


def fetch_names() -> list[str]:
    last = None
    for url in OVERPASS_ENDPOINTS:
        try:
            r = httpx.post(url, data={"data": QUERY}, timeout=200)
            r.raise_for_status()
            names = {e["tags"]["name:uk"].strip()
                     for e in r.json()["elements"] if e["tags"].get("name:uk")}
            return sorted(n for n in names if n)
        except Exception as exc:  # noqa: BLE001 — try the next mirror
            last = exc
    raise SystemExit(f"Overpass fetch failed on all endpoints: {last}")


def build_entry(name: str) -> dict:
    forms, seen = [], set()
    force_marker = name in FORCE_MARKER
    force_perm = name in FORCE_PERMISSIVE
    for f in sorted(inflect_forms(name), key=len, reverse=True):
        if f in seen:
            continue
        seen.add(f)
        if force_marker:
            marker = True
        elif force_perm:
            marker = False
        else:
            marker = is_common(f)
        forms.append({"f": f, "m": 1 if marker else 0})
    for tr in [transliterate(name), *ALT_TRANSLIT.get(name, [])]:
        if tr and tr not in seen:
            seen.add(tr)
            forms.append({"f": tr, "m": 1 if force_marker else 0})
    return {"name": name, "forms": forms}


def main() -> None:
    names = fetch_names()
    entries = [build_entry(n) for n in names]
    CRAWLER_OUT.write_text(json.dumps(entries, ensure_ascii=False, indent=0), encoding="utf-8")
    ADMIN_OUT.write_text(
        "// AUTO-GENERATED by crawler/scripts/build_gazetteer.py — do not edit by hand.\n"
        "export const GAZETTEER = " + json.dumps(names, ensure_ascii=False) + ";\n",
        encoding="utf-8")
    print(f"wrote {len(entries)} cities -> {CRAWLER_OUT} and {ADMIN_OUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
