"""crawler support

Revision ID: c04d4e4207e6
Revises: 244a89a3fd3c
Create Date: 2026-07-12 16:24:07.215847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c04d4e4207e6'
down_revision: Union[str, Sequence[str], None] = '244a89a3fd3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Enum('active', 'cooldown', 'banned', name='botaccountstate'), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'username', name='uq_bot_platform_username')
    )
    op.create_table('source_crawl_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('last_seen_key', sa.String(length=255), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.add_column('offers', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_offer_source_content_hash', 'offers', ['source_id', 'content_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # MySQL/InnoDB reused uq_offer_source_content_hash as the supporting index
    # for the offers.source_id FK (dropping the old single-column index it had
    # relied on). Recreate that index first so the FK still has a backing
    # index once the unique constraint is dropped.
    op.create_index('source_id', 'offers', ['source_id'])
    op.drop_constraint('uq_offer_source_content_hash', 'offers', type_='unique')
    op.drop_column('offers', 'content_hash')
    op.drop_table('source_crawl_state')
    op.drop_table('bot_accounts')
    # ### end Alembic commands ###
